"Pretty-ify" the frontend
gpuctl/gpuctl pull request #261
Opened 2024-03-06 17:15 UTC by danielg0

- [x] Shorten the page title and header
- [x] Center the Tab entries
- [x] Combine admin panel button and log-in into one
- [ ] Spacing
- [ ] Graph line colours

Really haven't written much frontend code, so do please look over.

2024-03-06 17:17 UTC, danielg0 commented
Starting from this

![Screenshot 2024-03-06 at 17-16-12 gpuctl - The GPU Control Room](https://github.com/gpuctl/gpuctl/assets/34688856/efdfdbf7-3855-48d9-95bf-eebb2a637455)

2024-03-06 17:18 UTC, danielg0 commented
The frontend now looks like this

![Screenshot 2024-03-06 at 17-17-16 G P U C T L](https://github.com/gpuctl/gpuctl/assets/34688856/aa86ddfd-d98b-4d76-8184-dcdfe03ddfde)

And when we're not logged in, clicking on the admin panel shows this

![2024-03-06_17 17 29](https://github.com/gpuctl/gpuctl/assets/34688856/af6ca766-9622-4ce4-bbb8-8b30ac4c11a8)

2024-03-06 19:25 UTC, danielg0 commented
With these changes to cards, they now look like

![Screenshot 2024-03-06 at 19-19-37 G P U C T L](https://github.com/gpuctl/gpuctl/assets/34688856/b3871342-57c3-441b-95a4-a23feb0340a5)

2024-03-06 19:37 UTC, NathanielB123 commented
> Starting from this
> 
> ![Screenshot 2024-03-06 at 17-16-12 gpuctl - The GPU Control Room](https://private-user-images.githubusercontent.com/34688856/310592990-efdfdbf7-3855-48d9-95bf-eebb2a637455.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NTQxMzgsIm5iZiI6MTcwOTc1MzgzOCwicGF0aCI6Ii8zNDY4ODg1Ni8zMTA1OTI5OTAtZWZkZmRiZjctMzg1NS00OGQ5LTk1YmYtZWViYjJhNjM3NDU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE5MzcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMWVhNjY3MzU5Mzk4ZmU0MGQyZGExMWE0Nzk4YmU4YjVlZjFiODMzYmI5YWEyNjkxZjI2Yzg1ZmZlYmJhOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iXi-0fOc7eV8-Y7PSX3GOS6qtpn0AGnZmEJG1wlMmls)

How do you sign out?

2024-03-06 19:46 UTC, danielg0 commented
Now the login box looks like

![2024-03-06_19 46 17](https://github.com/gpuctl/gpuctl/assets/34688856/b0ebaf05-fc34-428f-b6cb-a3ccaa1df237)

2024-03-06 19:48 UTC, danielg0 commented
> > And when we're not logged in, clicking on the admin panel shows this
> 
> How do you sign out?

There's a sign out button on the admin page

![Screenshot 2024-03-06 at 19-47-52 G P U C T L](https://github.com/gpuctl/gpuctl/assets/34688856/e7474230-3afc-4a6c-be1b-f49d2e064b4b)

2024-03-06 23:24 UTC, NathanielB123 commented
Frontend test should be easy to fix. After the paragraphs of warnings I think the root issue is we are still expecting to find "Welcome to GPU Control Room!" text somewhere, but obviously we can't.

2024-03-07 01:05 UTC, sirjacobofglais approved these changes

2024-03-07 01:05 UTC, sirjacobofglais commented on frontend/src/Pages/MainView.tsx
> +        // TODO: replace with actual aggregate data from backend
can we disable this component until the backend parts are ready?

2024-03-07 12:27 UTC, YRMYJASKA commented on frontend/src/Pages/MainView.tsx
> +        // TODO: replace with actual aggregate data from backend
aggregate stats have been done on the back-end since  #239  got merged

2024-03-07 14:09 UTC, NathanielB123 commented on frontend/src/Pages/MainView.tsx
> +        // TODO: replace with actual aggregate data from backend
Yeah I explicitly asked daniel to add this so wiring it up would be an easy future pr (instead of having to go through another UI prettify cycle)

2024-03-07 14:11 UTC, YRMYJASKA requested changes

2024-03-07 14:11 UTC, YRMYJASKA commented on frontend/src/Components/AggregateStats.tsx
> +  data: { average_use: number; uptime: string };
no, just no. This is not what im returning

2024-03-07 14:30 UTC, YRMYJASKA approved these changes

2024-03-07 15:23 UTC, merged